#!/usr/bin/env bash
# Script that that displays numbers from 1 to 100 but:
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is multiple of 3
# displays Buzz when the number is a multiple of 5
# otherwise, displays the number
for((num=1;num<101;num++))
do
    if [ $((num % 3)) -eq 0 ] || [ $((num % 5)) -eq 0 ]
    then
        if [ $((num % 3)) -eq 0 ]
        then
            printf "Fizz"
        fi
        if [ $((num % 5)) -eq 0 ]
        then
            printf "Buzz"
        fi
        echo
    else
         echo "$num"
    fi
done
