#!/usr/bin/env bash
# Simple script that prints Best School 10 times using a while loop
# And in the 9th iteration print Hi.

COUNTER=1

while [ $COUNTER -ne 11 ]
do
    echo 'Best School'

    if [ $COUNTER -eq 9 ]
    then
         echo 'Hi'
    fi

    COUNTER=$((COUNTER + 1))
done
