#!/usr/bin/env bash
# Simple function that that displays the content of the current directory
# in a list format where only the part of the name
# after the first dash is displayed.
for item in *
do
    echo "$item"
done | cut -f2 -d "-"
