#!/usr/bin/env bash
# Function that prints information about the school file.
# Information about existence, content and type.
if [ -e "school" ]
then
    echo "school file exists"
    if [ -s "school" ]
    then
         echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "school" ]
    then
         echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
